# Site settings
title: Anvar Mohamed Aslam Sha – Data & Business Analyst
email: akcentrox@gmail.com
url: https://github.com/aslamshaw
description: "Anvar Mohamed Aslam Sha is a Data & Business Analyst specializing in predictive modeling, dashboard development, and data-driven decision-making. Passionate about transforming complex data into strategic insights."
keywords: "Data Analyst, Business Analyst, Predictive Modeling, Power BI, Python, Machine Learning, Freelance Analyst, Dashboard Developer, Aslam Sha"
skills: "Data Analyst - Business Intelligence - Predictive Modeling - Machine Learning"
meta_author: Anvar Mohamed Aslam Sha

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Anvar Mohamed Aslam Sha
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://stackoverflow.com/questions/tagged/aslam-sha
  - title: linkedin
    url: https://linkedin.com/in/aslamshaw
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: No.3/61, Peria Pallivasal St, Pakkiripalayam, Panruti
  - line: 607112 Tamil Nadu, India

# Credits content
credits: 'Designed and customized by Anvar Mohamed Aslam Sha using the Freelancer Jekyll Theme from <a href="https://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
